import type { Flow } from '../types'

export const flow: Flow = {
  id: 24,
  section: 'Governance & Planning',
  mode: 'Both',
  title: 'View Goals & Track Progress',
  summary:
    'Overview of all tribe goals, milestone completion status, task completion rates, and deadline tracking.',
  steps: [
    {
      n: '1a',
      screen: 'Goals Overview — empty',
      route: '/tribe/{TRIBE}/goals',
      desc: 'No goals yet. "No goals" empty state. "New Goal" CTA.',
      action: 'Observe the empty goals state.',
    },
    {
      n: '1b',
      screen: 'Goals Overview — populated',
      route: '/tribe/{TRIBE}/goals',
      desc: 'Goals list with progress bars, milestone indicators, task completion counts, deadline badges. Filter by status (Active/Completed/Overdue). Tap to expand full details.',
      action: 'Review goals. Tap a task to mark it complete. Observe progress bar update.',
      injectIDB: [
        {
          store: 'tribe-goals',
          key: '{TRIBE}:goal001',
          data: {
            id: 'goal001',
            tribeId: '{TRIBE}',
            title: 'Build 3-month food cache',
            status: 'active',
            horizon: 'short_term',
            createdAt: '{NOW-5d}',
            createdBy: '{SELF_PUB}',
          },
        },
        {
          store: 'tribe-goals',
          key: '{TRIBE}:goal002',
          data: {
            id: 'goal002',
            tribeId: '{TRIBE}',
            title: 'Establish HAM radio comms',
            status: 'active',
            horizon: 'medium_term',
            createdAt: '{NOW-10d}',
            createdBy: 'dummy_pub_3_jordan_blake',
          },
        },
        {
          store: 'tribe-tasks',
          key: '{TRIBE}:task001',
          data: {
            id: 'task001',
            tribeId: '{TRIBE}',
            goalId: 'goal001',
            title: 'Research FoodCo bulk pricing',
            status: 'done',
            assignedTo: ['dummy_pub_2_sam_chen'],
            dueDate: '{NOW-3d}',
            createdAt: '{NOW-5d}',
          },
        },
        {
          store: 'tribe-tasks',
          key: '{TRIBE}:task002',
          data: {
            id: 'task002',
            tribeId: '{TRIBE}',
            goalId: 'goal001',
            title: 'Source #10 cans',
            status: 'in_progress',
            assignedTo: ['{SELF_PUB}'],
            dueDate: '{NOW+5d}',
            createdAt: '{NOW-4d}',
          },
        },
        {
          store: 'tribe-tasks',
          key: '{TRIBE}:task003',
          data: {
            id: 'task003',
            tribeId: '{TRIBE}',
            goalId: 'goal001',
            title: 'Organize storage rotation',
            status: 'todo',
            assignedTo: ['dummy_pub_3_jordan_blake'],
            dueDate: '{NOW+14d}',
            createdAt: '{NOW-3d}',
          },
        },
        {
          store: 'tribe-tasks',
          key: '{TRIBE}:task004',
          data: {
            id: 'task004',
            tribeId: '{TRIBE}',
            goalId: 'goal002',
            title: 'Get HAM Technician license',
            status: 'in_progress',
            assignedTo: ['{SELF_PUB}', 'dummy_pub_2_sam_chen'],
            dueDate: '{NOW+30d}',
            createdAt: '{NOW-10d}',
          },
        },
        {
          store: 'goal-milestones',
          key: '{TRIBE}:ms001',
          data: {
            id: 'ms001',
            tribeId: '{TRIBE}',
            goalId: 'goal001',
            title: 'Research complete',
            status: 'done',
            dueDate: '{NOW-2d}',
          },
        },
        {
          store: 'goal-milestones',
          key: '{TRIBE}:ms002',
          data: {
            id: 'ms002',
            tribeId: '{TRIBE}',
            goalId: 'goal001',
            title: 'Purchase complete',
            status: 'in_progress',
            dueDate: '{NOW+7d}',
          },
        },
        {
          store: 'goal-milestones',
          key: '{TRIBE}:ms003',
          data: {
            id: 'ms003',
            tribeId: '{TRIBE}',
            goalId: 'goal002',
            title: 'All members licensed',
            status: 'in_progress',
            dueDate: '{NOW+60d}',
          },
        },
      ],
    },
  ],
}
